# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: flow.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='flow.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\nflow.proto\"e\n\x0bProtoSchema\x12$\n\x07\x63olumns\x18\x01 \x03(\x0b\x32\x13.ProtoSchema.Column\x1a\x30\n\x06\x43olumn\x12\x18\n\x04type\x18\x01 \x01(\x0e\x32\n.ProtoType\x12\x0c\n\x04name\x18\x02 \x01(\t\"m\n\nProtoTable\x12\x1c\n\x06schema\x18\x01 \x01(\x0b\x32\x0c.ProtoSchema\x12\x1d\n\x04rows\x18\x02 \x03(\x0b\x32\x0f.ProtoTable.Row\x1a\"\n\x03Row\x12\x0b\n\x03qid\x18\x01 \x01(\x03\x12\x0e\n\x06values\x18\x02 \x03(\x0c*S\n\tProtoType\x12\x07\n\x03INT\x10\x00\x12\x0e\n\nFLOWSTRING\x10\x01\x12\x08\n\x04\x42OOL\x10\x02\x12\t\n\x05\x42YTES\x10\x03\x12\t\n\x05\x46LOAT\x10\x04\x12\r\n\tFLOWNUMPY\x10\x05\x62\x06proto3')
)

_PROTOTYPE = _descriptor.EnumDescriptor(
  name='ProtoType',
  full_name='ProtoType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='INT', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FLOWSTRING', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BOOL', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BYTES', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FLOAT', index=4, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FLOWNUMPY', index=5, number=5,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=228,
  serialized_end=311,
)
_sym_db.RegisterEnumDescriptor(_PROTOTYPE)

ProtoType = enum_type_wrapper.EnumTypeWrapper(_PROTOTYPE)
INT = 0
FLOWSTRING = 1
BOOL = 2
BYTES = 3
FLOAT = 4
FLOWNUMPY = 5



_PROTOSCHEMA_COLUMN = _descriptor.Descriptor(
  name='Column',
  full_name='ProtoSchema.Column',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='ProtoSchema.Column.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='ProtoSchema.Column.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=67,
  serialized_end=115,
)

_PROTOSCHEMA = _descriptor.Descriptor(
  name='ProtoSchema',
  full_name='ProtoSchema',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='columns', full_name='ProtoSchema.columns', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_PROTOSCHEMA_COLUMN, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=14,
  serialized_end=115,
)


_PROTOTABLE_ROW = _descriptor.Descriptor(
  name='Row',
  full_name='ProtoTable.Row',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='qid', full_name='ProtoTable.Row.qid', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='values', full_name='ProtoTable.Row.values', index=1,
      number=2, type=12, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=192,
  serialized_end=226,
)

_PROTOTABLE = _descriptor.Descriptor(
  name='ProtoTable',
  full_name='ProtoTable',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='schema', full_name='ProtoTable.schema', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rows', full_name='ProtoTable.rows', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_PROTOTABLE_ROW, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=117,
  serialized_end=226,
)

_PROTOSCHEMA_COLUMN.fields_by_name['type'].enum_type = _PROTOTYPE
_PROTOSCHEMA_COLUMN.containing_type = _PROTOSCHEMA
_PROTOSCHEMA.fields_by_name['columns'].message_type = _PROTOSCHEMA_COLUMN
_PROTOTABLE_ROW.containing_type = _PROTOTABLE
_PROTOTABLE.fields_by_name['schema'].message_type = _PROTOSCHEMA
_PROTOTABLE.fields_by_name['rows'].message_type = _PROTOTABLE_ROW
DESCRIPTOR.message_types_by_name['ProtoSchema'] = _PROTOSCHEMA
DESCRIPTOR.message_types_by_name['ProtoTable'] = _PROTOTABLE
DESCRIPTOR.enum_types_by_name['ProtoType'] = _PROTOTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ProtoSchema = _reflection.GeneratedProtocolMessageType('ProtoSchema', (_message.Message,), dict(

  Column = _reflection.GeneratedProtocolMessageType('Column', (_message.Message,), dict(
    DESCRIPTOR = _PROTOSCHEMA_COLUMN,
    __module__ = 'flow_pb2'
    # @@protoc_insertion_point(class_scope:ProtoSchema.Column)
    ))
  ,
  DESCRIPTOR = _PROTOSCHEMA,
  __module__ = 'flow_pb2'
  # @@protoc_insertion_point(class_scope:ProtoSchema)
  ))
_sym_db.RegisterMessage(ProtoSchema)
_sym_db.RegisterMessage(ProtoSchema.Column)

ProtoTable = _reflection.GeneratedProtocolMessageType('ProtoTable', (_message.Message,), dict(

  Row = _reflection.GeneratedProtocolMessageType('Row', (_message.Message,), dict(
    DESCRIPTOR = _PROTOTABLE_ROW,
    __module__ = 'flow_pb2'
    # @@protoc_insertion_point(class_scope:ProtoTable.Row)
    ))
  ,
  DESCRIPTOR = _PROTOTABLE,
  __module__ = 'flow_pb2'
  # @@protoc_insertion_point(class_scope:ProtoTable)
  ))
_sym_db.RegisterMessage(ProtoTable)
_sym_db.RegisterMessage(ProtoTable.Row)


# @@protoc_insertion_point(module_scope)
